[package]
name = "rbxapi"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.61.1", features = ["Win32_System_LibraryLoader", "Win32_System_Threading"] }
offsets = { path = "../offsets" }