[package]
name = "e4rthbyte"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.45.1", features = ["time", "rt"] }
rbxapi = { path = "rbxapi" }
luau = { path = "luau" }
panichook = { path = "panichook" }