[package]
name = "e4rthbyte"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
smol = "2.0.2"
rbxapi = { path = "rbxapi" }
luau = { path = "luau" }
panichook = { path = "panichook" }