[package]
name = "e4rthbyte"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.61.1", features = ["Win32_System_LibraryLoader", "Win32_System_Threading"] }